/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzx_factorytest_manager_NativeManager */

#ifndef _Included_com_zzx_factorytest_manager_NativeManager
#define _Included_com_zzx_factorytest_manager_NativeManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzx_factorytest_manager_NativeManager
 * Method:    getCorrectResult
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zzx_factorytest_manager_NativeManager_getCorrectResult
  (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
